### ISSUE TITLE
Issue on code

### ISSUE THREAD

**Issue by sahadevgh** [Tunteeya/My-first-contract#1]
### Correct your contract declaration
- After checking your code, I realized that you didn't declare the SimpleStorage contract but only created a function.
- This is wrong, you have to follow the steps of lesson 1.3 of the solidity programming 101 to have a correct code.
- You start by first declaring the contract SimpleStorage. The you add the FavoriteNumber variable

**Comment by Tunteeya** [comment]
I appreciate your feedback sir. The correction has been implemented.

**Comment by sahadevgh** [comment]
You are welcome. Your code is now correct
